# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-12 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='', max_length=109)),
                ('loan_type', models.CharField(choices=[('fixed_rate', 'Fixed Rate'), ('float_rate', 'Floating Rate'), ('both', 'Both')], default='fixed_rate', max_length=10)),
                ('property_type', models.CharField(choices=[('CM', 'Commerical'), ('HDB', 'HDB'), ('PP', 'Private')], default='PP', max_length=2)),
                ('bank_image', models.ImageField(upload_to='bank_images/')),
                ('loan_tenure', models.IntegerField()),
                ('interest_rates', models.FloatField()),
            ],
        ),
    ]
