# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='', max_length=109)),
                ('loan_type', models.CharField(choices=[('fixed_rate', 'Fixed Rate'), ('float_rate', 'Floating Rate'), ('both', 'Both')], default='fixed_rate', max_length=10)),
                ('property_type', models.CharField(choices=[('CM', 'Commerical'), ('HDB', 'HDB'), ('PP', 'Private')], default='PP', max_length=2)),
                ('bank_image', models.CharField(choices=[('http://127.0.0.1:8000/media/bank_images/dbs_logo.jpg', 'DBS'), ('http://127.0.0.1:8000/media/bank_images/uob_logo.png', 'UOB'), ('http://127.0.0.1:8000/media/bank_images/uob_logo.png', 'Standard Charter'), ('http://127.0.0.1:8000/media/bank_images/maybank_logo.png', 'Maybank'), ('http://127.0.0.1:8000/media/bank_images/hong_leong.jpg', 'Hong Leong Finance'), ('http://127.0.0.1:8000/media/bank_images/bea_logo.png', 'BEA'), ('http://127.0.0.1:8000/media/bank_images/ocbc_logo.png', 'OCBC'), ('http://127.0.0.1:8000/media/bank_images/posb_logo.png', 'POSB'), ('http://127.0.0.1:8000/media/bank_images/rhb_bank.png', 'RHB')], default='', max_length=200)),
                ('loan_tenure', models.IntegerField()),
                ('interest_rates', models.FloatField()),
            ],
            options={
                'ordering': ('interest_rates',),
            },
        ),
    ]
