# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-12 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrates',
            name='bank_image',
            field=models.CharField(choices=[('http://127.0.0.1:8000/media/bank_images/dbs_logo.jpg', 'DBS'), ('http://127.0.0.1:8000/media/bank_images/uob_logo.png', 'UOB')], default='', max_length=200),
        ),
    ]
