# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-15 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrates',
            name='property_type',
            field=models.CharField(choices=[('CM', 'Commerical'), ('HDB', 'HDB'), ('PP', 'Private')], default='PP', max_length=20),
        ),
    ]
